spring.application.name=GrievanceService
server.port=8082

# Database configuration
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/civicpulse_grievance_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:21030-Cm-108}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true        

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB


azure.storage.connection-string=${AZURE_STORAGE_CONNECTION_STRING:DefaultEndpointsProtocol=https;AccountName=musicstream;AccountKey=FYKTDaRgzmwrlSfxuYRezlC6R9/4Pf59OpWnWuLFY2fbTAz/yPLuQc+N2usTFV2AuOWQiY7UWTDd+AStIurn9Q==;EndpointSuffix=core.windows.net}
azure.storage.container-name=civicpulse-images